"""initial schema

Revision ID: 838b9842bac0
Revises:
Create Date: 2026-07-10 16:15:19.217071

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "838b9842bac0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auction_items",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_item_id", sa.String(length=200), nullable=True),
        sa.Column("auction_type", sa.String(length=50), nullable=False),
        sa.Column("case_number", sa.String(length=100), nullable=True),
        sa.Column("item_number", sa.String(length=50), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("sub_category", sa.String(length=50), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("sido", sa.String(length=50), nullable=True),
        sa.Column("sigungu", sa.String(length=50), nullable=True),
        sa.Column("eupmyeondong", sa.String(length=50), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("appraisal_price", sa.BigInteger(), nullable=True),
        sa.Column("minimum_price", sa.BigInteger(), nullable=True),
        sa.Column("deposit_price", sa.BigInteger(), nullable=True),
        sa.Column("bid_date", sa.DateTime(), nullable=True),
        sa.Column("bid_location", sa.Text(), nullable=True),
        sa.Column("fail_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("status", sa.String(length=50), server_default="active", nullable=True),
        sa.Column("view_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("watch_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("raw_source_record_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "collection_jobs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("fetched_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("inserted_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updated_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "property_transactions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("property_type", sa.String(length=50), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("sido", sa.String(length=50), nullable=True),
        sa.Column("sigungu", sa.String(length=50), nullable=True),
        sa.Column("eupmyeondong", sa.String(length=50), nullable=True),
        sa.Column("complex_name", sa.String(length=200), nullable=True),
        sa.Column("exclusive_area", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("deal_price", sa.BigInteger(), nullable=True),
        sa.Column("deal_year", sa.Integer(), nullable=True),
        sa.Column("deal_month", sa.Integer(), nullable=True),
        sa.Column("deal_day", sa.Integer(), nullable=True),
        sa.Column("floor_info", sa.String(length=50), nullable=True),
        sa.Column("build_year", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raw_source_records",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_record_id", sa.String(length=200), nullable=True),
        sa.Column("record_type", sa.String(length=50), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.Text(), nullable=True),
        sa.Column("nickname", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "auction_results",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("auction_item_id", sa.BigInteger(), nullable=True),
        sa.Column("result_status", sa.String(length=50), nullable=True),
        sa.Column("winning_price", sa.BigInteger(), nullable=True),
        sa.Column("winning_rate", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("bidder_count", sa.Integer(), nullable=True),
        sa.Column("result_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["auction_item_id"], ["auction_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("auction_item_id", sa.BigInteger(), nullable=True),
        sa.Column("notification_type", sa.String(length=50), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), server_default="pending", nullable=True),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["auction_item_id"], ["auction_items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "price_predictions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("auction_item_id", sa.BigInteger(), nullable=True),
        sa.Column("predicted_price_low", sa.BigInteger(), nullable=True),
        sa.Column("predicted_price_mid", sa.BigInteger(), nullable=True),
        sa.Column("predicted_price_high", sa.BigInteger(), nullable=True),
        sa.Column("predicted_rate_low", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("predicted_rate_mid", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("predicted_rate_high", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("confidence", sa.String(length=50), nullable=True),
        sa.Column("model_version", sa.String(length=50), nullable=True),
        sa.Column("explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("disclaimer", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["auction_item_id"], ["auction_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "real_estate_details",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("auction_item_id", sa.BigInteger(), nullable=True),
        sa.Column("building_area", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("land_area", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("exclusive_area", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("floor_info", sa.String(length=100), nullable=True),
        sa.Column("approval_date", sa.Date(), nullable=True),
        sa.Column("land_rights", sa.Text(), nullable=True),
        sa.Column("building_structure", sa.Text(), nullable=True),
        sa.Column("usage_type", sa.String(length=100), nullable=True),
        sa.Column("appraisal_summary", sa.Text(), nullable=True),
        sa.Column("occupancy_summary", sa.Text(), nullable=True),
        sa.Column("tenant_summary", sa.Text(), nullable=True),
        sa.Column("registry_summary", sa.Text(), nullable=True),
        sa.Column("document_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["auction_item_id"], ["auction_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "risk_assessments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("auction_item_id", sa.BigInteger(), nullable=True),
        sa.Column("risk_level", sa.String(length=50), nullable=True),
        sa.Column("legal_risk_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("occupancy_risk_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("asset_risk_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("risk_factors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("disclaimer", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["auction_item_id"], ["auction_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "saved_searches",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("alert_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_watchlist",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("auction_item_id", sa.BigInteger(), nullable=True),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["auction_item_id"], ["auction_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "auction_item_id", name="uq_user_watchlist_user_item"),
    )
    op.create_table(
        "vehicle_details",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("auction_item_id", sa.BigInteger(), nullable=True),
        sa.Column("manufacturer", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("trim", sa.String(length=100), nullable=True),
        sa.Column("model_year", sa.Integer(), nullable=True),
        sa.Column("mileage", sa.Integer(), nullable=True),
        sa.Column("fuel_type", sa.String(length=50), nullable=True),
        sa.Column("transmission", sa.String(length=50), nullable=True),
        sa.Column("color", sa.String(length=50), nullable=True),
        sa.Column("accident_history", sa.Text(), nullable=True),
        sa.Column("inspection_summary", sa.Text(), nullable=True),
        sa.Column("storage_location", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["auction_item_id"], ["auction_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vehicle_details")
    op.drop_table("user_watchlist")
    op.drop_table("saved_searches")
    op.drop_table("risk_assessments")
    op.drop_table("real_estate_details")
    op.drop_table("price_predictions")
    op.drop_table("notifications")
    op.drop_table("auction_results")
    op.drop_table("users")
    op.drop_table("raw_source_records")
    op.drop_table("property_transactions")
    op.drop_table("collection_jobs")
    op.drop_table("auction_items")
    # ### end Alembic commands ###
